#!/usr/bin/perl

$line = <STDIN>;                 # 讀入鍵盤輸入，以 Carriage Return 作結～

if ($line eq "\n")               # STDIN 會自動加上 \n ，只有 \n 代表沒有特別輸入
{
    print "Nothing to print.\n";
}
else
{
    print "Input is : $line";
}
