#!/usr/bin/perl -w
use strict;

my ($base, $ans) = (2, 0);

if ($#ARGV > 1 or $#ARGV < 0) {
    die "usage: log number [base]\n";
} elsif ($#ARGV == 1) {
    $base = $ARGV[1];
}

my ($n) = $ARGV[0];

while ($n > 1) {
    $n /= $base;
    ++$ans;
}

print "log($ARGV[0]) base $base is roughly $ans\n";
